routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/blog/{post}', 'WelcomeController@show')->name('blog.show');
Route::get('/blog/category/{category}', 'WelcomeController@category')->name('blog.category');
Route::get('/blog/tag/{tag}', 'WelcomeController@tag')->name('blog.tag');



Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');
    Route::delete('/trash/{post}', 'PostsController@trash')->name('posts.trash');
    Route::get('/trashed', 'PostsController@trashed')->name('posts.trashed');
    Route::put('/restore/{post_id}', 'PostsController@restore')->name('posts.restore');
});
Route::middleware(['auth', 'verifyAdmin'])->group(function () {
    Route::get('/users', 'UsersController@index')->name('users.index');
    Route::put('/users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.makeAdmin');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    protected $dates = ['published_at'];
    protected $fillable = ['title', 'excerpt', 'content', 'image', 'published_at', 'category_id', 'tags', 'user_id'];

    /**
     * RELATIONSHIP METHODS
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * QUERY SCOPE
     */
    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now());
    }
    public function scopeSearch($query)
    {
        $search = request('search');
        // dd($search);
        if($search)
        {
            return $query->where('title', 'like', "%$search%");
        }
        return $query;
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\posts\CreatePostRequest;
use App\Http\Requests\posts\UpdatePostRequest;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->middleware('verifyCategoriesCount')->only('create', 'store');
        $this->middleware('validateAuthor')->only('edit', 'update', 'destroy', 'trash');
    }
    public function index()
    {
        if(!auth()->user()->isAdmin())
        {
            $posts = Post::withoutTrashed()->where('user_id' , auth()->id())->paginate(10);
        }
        else{

            $posts = Post::paginate(10);
        }
        return view('posts.index', compact([
            'posts'
        ]));
    }
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.create', compact([
            'categories' ,
            'tags'
        ]));
    }
    public function store(CreatePostRequest $request)
    {
        //Image upload  and stores the name of the image

        // dd($request->tags);

        $image = $request->file('image')->store('posts');

        //Image upload  and stores the name of the image
        $post = Post::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'content' => $request->content,
            'image' => $image,
            'published_at' => $request->published_at,
            'user_id' => auth()->id(),
            'category_id' => $request->category
        ]);

        $post->tags()->attach($request->tags);

        //Session storage
        session()->flash('success', 'Post Created Successfully');

        //redirect
        return redirect(route('posts.index'));

        /**
         * These are the 4 steps of creation
         *  i.e
         *
         * Image upload  and stores the name of the image
         * Create post
         * Session storage
         * redirect
         */
    }
    public function show(Post $post)
    {
        //
    }
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.edit', compact([
            'post',
            'categories',
            'tags'
        ]));
    }
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only(['title', 'excerpt', 'content', 'published_at', 'category_id']);
        if($request->hasFile('image'))
        {
            //Here my deleteImage() was not working
            // $post->deleteImage();
            File::delete(public_path('storage/'.$post->image));
            $image = $request->image->store('posts');
            $data['image'] = $image;
        }
        $post->update($data);
        if($request->tags)
        {
            $post->tags()->sync($request->tags);
        }
        session()->flash('success', 'Post Updated Successfully');
        return redirect(route('posts.index'));

    }
    public function destroy($id)
    {
        // dd($id);
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->forceDelete();
        session()->flash('success', 'Post Permenantely Deleted Successfully');
        return redirect(route('posts.trashed'));
    }

    /**
     * Soft Deletes
     */
    public function trash(Post $post)
    {
        // dd("HEllo");
        $post->delete();
        session()->flash('success', 'Post Deleted Successfully');
        return redirect(route('posts.index'));
    }
    public function trashed()
    {
        $posts = Post::onlyTrashed()->paginate(10);
        // $trashed = Post::withTrashed(); //name se he difference pechan lo
        return view('posts.trashed', compact([
            'posts'
        ]));
    }
    public function restore($post_id)
    {
        $post = Post::onlyTrashed()->find($post_id);
        $post->deleted_at = null;
        $post->save();
        session()->flash('success', 'Post Restored Successfully');
        return redirect(route('posts.trashed'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Add Post</div>
        <div class="card-body">
            <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                            value="{{ old('title') }}"
                            class="form-control @error('title') is-invalid @enderror"
                            name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <textarea name="excerpt" id="excerpt" rows="4" class="form-control @error('excerpt') is-invalid @enderror" >{{ old('excerpt') }}</textarea>
                    @error('excerpt')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <input type="hidden" id="content" name="content" value="{{ old('content') }}">
                    <trix-editor input="content"></trix-editor>
                    @error('content')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="category">Category</label>
                    <select name="category" id="category" class="form-control">
                        <option value="-1" disabled selected>Select ... </option>
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                    @error('category')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="tag">Tags</label>
                    <select name="tags[]" id="tag" class="form-control select2" multiple>
                        @foreach ($tags as $tag)
                            <option
                                value="{{ $tag->id }}"
                                {{
                                    old('tags') ?
                                    (in_array($tag->id, old('tags')) ? 'selected' : '') : ''
                                }}>
                                {{ $tag->name }}
                            </option>
                        @endforeach
                    </select>
                    @error('tag')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="date"
                            value="{{ old('published_at') }}"
                            class="form-control"
                            name="published_at" id="published_at">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file"
                            value="{{ old('image') }}"
                            class="form-control @error('image') is-invalid @enderror"
                            name="image" id="image">
                    @error('image')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Add Post</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('page-level-scripts')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
        $(document).ready(function(){
        });

        // Here this select2 code or function first written inside the document.ready but it fails, but when i put this method outside the ready function it works fine, i rlly dont know the reason why it behaves like this, but this is some kind of memory or can say mistake done from me, and its not wrong to place this select2 inside the ready, everybody's code was running fine inside the ready, but for mine , i dont know (english ke liye itna likha ;) )
        $('.select2').select2({
            placeholder : 'Select..'
        });
    </script>
@endsection

@section('page-level-styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Add Post</div>
        <div class="card-body">
            <form action="{{ route('posts.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                            value="{{ old('title', $post->title) }}"
                            class="form-control @error('title') is-invalid @enderror"
                            name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <textarea name="excerpt"
                    id="excerpt" rows="4"
                    class="form-control
                    @error('excerpt') is-invalid @enderror" >{{ old('excerpt', $post->excerpt) }}</textarea>
                    @error('excerpt')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <input type="hidden" id="content" name="content" value="{{ old('content',$post->content) }}">
                    <trix-editor input="content"></trix-editor>
                    @error('content')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="category">Category</label>
                    <select name="category_id" id="category_id" class="form-control">
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}" {{ $category->id == $post->category_id ? 'selected' : '' }}>{{ $category->name }}</option>
                        @endforeach
                    </select>
                    @error('category')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="tag">Tags</label>
                    <select name="tags[]" id="tag" class="form-control select2" multiple>
                        @foreach ($tags as $tag)
                            <option
                                value="{{ $tag->id }}"
                                {{
                                    old('tags') ?
                                    (in_array($tag->id, old('tags')) ? 'selected' : '')
                                    : ($tag->id == $post->tags->contains($tag) ? 'selected' : '')
                                }}>
                            {{ $tag->name }}
                            </option>
                        @endforeach
                    </select>
                    @error('tag')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text"
                            value="{{  $post->published_at }}"
                            class="form-control"
                            name="published_at" id="published_at"
                            >
                </div>
                <div class="form-group">
                    <img src="{{ asset('storage/' . $post->image) }}" alt="edit-image" width="100%">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file"
                            class="form-control @error('image') is-invalid @enderror"
                            name="image" id="image">
                    @error('image')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-warning" type="submit">Edit Post</button>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
        $(document).ready(function(){
        });
        $('.select2').select2();
    </script>
@endsection

@section('page-level-styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Post</a>
    </div>

    <div class="card">


        <div class="card-header">Posts</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Author</th>
                    <th>Category</th>
                    <th>Tags</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset('storage/'.$post->image) }}" alt="" width="128px"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>{{ $post->author->name }}</td>
                            <td>{{ $post->category->name }}</td>
                            <td>
                                @foreach ($post->tags as $tag)
                                    {{ $tag->name }}
                                @endforeach
                            </td>
                            <td>
                                <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-outline-primary btn-sm">Edit</a>
                                <a href=""
                                    class="btn btn-outline-danger btn-sm"
                                    onclick="displayModalForm({{ $post }})"
                                    data-toggle="modal"
                                    data-target="#deleteModal">Trash</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{ $posts->links() }}
        </div>
    </div>

    <!-- DELETE Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModal">Delete Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    Are your sure you want to delete post
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete Post</button>
                </div>
            </form>
        </div>
        </div>
    </div>
    <!-- END Delete Modal-->

@endsection
@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($post)
        {
            var url = '/trash/' + $post.id;
            $('#deleteForm').attr('action', url);
        }
    </script>
@endsection

resources/views/posts/trashed.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">


        <div class="card-header">Posts</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    <th>Tags</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset('storage/'.$post->image) }}" alt="" width="128px"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>{{ $post->category->name }}</td>
                            <td>
                                @foreach ($post->tags as $tag)
                                    {{ $tag->name }}
                                @endforeach
                            </td>
                            <td>
                                <a href=""
                                    class="btn btn-outline-primary btn-sm"
                                    onclick="displayRestoreModalForm({{ $post }})"
                                    data-toggle="modal"
                                    data-target="#restoreModal">Restore</a>
                                <a href=""
                                    class="btn btn-outline-danger btn-sm"
                                    onclick="displayModalForm({{ $post }})"
                                    data-toggle="modal"
                                    data-target="#deleteModal">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{ $posts->links() }}
        </div>
    </div>


    <!-- RESTORE Modal -->
    <div class="modal fade" id="restoreModal" tabindex="-1" role="dialog" aria-labelledby="restoreModal" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="restoreModal">Restore Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form action="" method="POST" id="restoreForm">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    Are your sure you want to restore this post Permenantely
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Restore Post</button>
                </div>
            </form>
        </div>
        </div>
    </div>
    <!-- END Restore Modal-->

    <!-- DELETE Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModal">Delete Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    Are your sure you want to delete this post Permenantely
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete Post Permenantely</button>
                </div>
            </form>
        </div>
        </div>
    </div>
    <!-- END Delete Modal-->

@endsection
@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($post)
        {
            var url = '/posts/' + $post.id;
            $('#deleteForm').attr('action', url);
        }
        function displayRestoreModalForm($post)
        {
            var url = '/restore/' + $post.id;
            $('#restoreForm').attr('action', url);
        }
    </script>
@endsection